Added local data source, also modified with suspend some classes
OscarAntona/RSS-APP pull request #6
Opened 2022-11-16 16:56 UTC by OscarAntona

## Task description
In this task we had to choose one local data source
## ¿Cómo se ha implementado?
I decided to use XML as a local data source, because it was really easy to implement as we only are asking for a name and a url, I also added suspend so that I dont have problems when implementing coroutines
## Keywords
LocalDataSource, XML, Suspend

2022-11-16 22:12 UTC, dherranz1 reviewed
Aporto algunas apreciaciones y posibles mejoras de código :technologist:

2022-11-16 22:20 UTC, OscarAntona commented
Si, tienes razón, creo que sí seria mejor usar la URL como clave y efectivamente se me olvidó el apply, muchas gracias, esperaré a ver qué dice Chema y ya hago los cambios

2022-11-22 14:35 UTC, josem-perram commented on app/src/main/java/com/antgut/rss_app/management/domain/RssRepository.kt
> +    suspend fun saveRss(rssModel: ManagementModel)
Spanish please. Eso es @dherranz1, hay que seguir las especificaciones del ticket.

2022-11-22 14:37 UTC, josem-perram requested changes
@OscarAntona, opino igual que @dherranz1, please, revisa los comentarios.

2022-11-22 15:32 UTC, dherranz1 approved these changes
👍

2022-11-23 14:29 UTC, josem-perram approved these changes
Ok, todo OK.

2022-11-23 14:34 UTC, merged